// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 12.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Globalization;
using System.Reflection;
using System.Text;
using Assets.Scripts.Utilities;

namespace Assets.Editor.ScriptParams
{
    /// <summary>
    ///     A class that generates the text template for a <see cref="ScriptParams{T}" /> stub. This
    ///     was borrowed / generated by a tool, so it's a little bit more complex than need be.
    /// </summary>
    public class ScriptParamsStubTemplate : StringItemsGeneratorBase
    {
        private readonly Type paramsType;

        /// <summary>Stores the class name of the class that owns the params inner class.</summary>
        private readonly string paramsOuterClassName;

        /// <summary>Stores the class name of the inner ScriptParams class.</summary>
        private readonly string paramsInnerClassName;

        public ScriptParamsStubTemplate(Type paramsType)
        {
            this.paramsType = paramsType;
            paramsInnerClassName = this.paramsType.Name;
            paramsOuterClassName = this.paramsType.DeclaringType.Name;
        }

        /// <summary>Create the template output. This is the meat of the file.</summary>
        public string GenerateText()
        {
            // Summary
            Write("//------------------------------------------------------------------------------\r\n"
                  + "// <auto-generated>\r\n"
                  + "// This code was generated by an Editor script (ScriptParamsStubTemplate.cs).\r\n"
                  + "// </auto-generated>\r\n"
                  + "//------------------------------------------------------------------------------\r\n"
                  + "using UnityEngine;\r\n"
                  + "using ");
            Write(paramsType.Namespace);
            Write(";\r\n"
                  + "/// <summary>\r\n"
                  + "/// A stub / dummy class for the ");

            Write(paramsOuterClassName);

            Write(" ScriptParams class. \r\n" +
                  "/// Only exists so Unity can instantiate this class as an asset.\r\n" +
                  "/// </summary>\r\n");

            // Attribute
            Write("[CreateAssetMenu(fileName = \"");
            Write(paramsOuterClassName);
            Write("Params\", menuName = \"ASG/ScriptParams/");
            Write(paramsOuterClassName);
            Write("Params\", order = 1)] \r\n");

            // Class definition
            Write("public class ");
            Write(paramsOuterClassName);
            Write("Params : ");
            Write(paramsOuterClassName);
            Write(".");
            Write(paramsInnerClassName);
            Write("\r\n" +
                  "{\r\n" +
                  "}\r\n");
            return GenerationEnvironment.ToString();
        }
    }

    #region Base class

    /// <summary>Base class for this transformation</summary>
    [GeneratedCode("Microsoft.VisualStudio.TextTemplating", "12.0.0.0")]
    public class StringItemsGeneratorBase
    {
        #region Fields

        private StringBuilder generationEnvironmentField;
        private List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;

        #endregion

        #region Properties

        /// <summary>The string builder that generation-time code is using to assemble generated output</summary>
        protected StringBuilder GenerationEnvironment
        {
            get
            {
                if (generationEnvironmentField == null)
                {
                    generationEnvironmentField = new StringBuilder();
                }

                return generationEnvironmentField;
            }
            set { generationEnvironmentField = value; }
        }

        /// <summary>A list of the lengths of each indent that was added with PushIndent</summary>
        private List<int> indentLengths
        {
            get
            {
                if (indentLengthsField == null)
                {
                    indentLengthsField = new List<int>();
                }

                return indentLengthsField;
            }
        }

        /// <summary>Gets the current indent we use when adding lines to the output</summary>
        public string CurrentIndent
        {
            get { return currentIndentField; }
        }

        /// <summary>Current transformation session</summary>
        public IDictionary<string, object> Session { get; set; }

        #endregion

        #region Transform-time helpers

        /// <summary>Write text directly into the generated output</summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }

            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (GenerationEnvironment.Length == 0
                || endsWithNewline)
            {
                GenerationEnvironment.Append(currentIndentField);
                endsWithNewline = false;
            }

            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(Environment.NewLine, StringComparison.CurrentCulture))
            {
                endsWithNewline = true;
            }

            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if (currentIndentField.Length == 0)
            {
                GenerationEnvironment.Append(textToAppend);
                return;
            }

            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(Environment.NewLine, Environment.NewLine + currentIndentField);
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (endsWithNewline)
            {
                GenerationEnvironment.Append(textToAppend, 0, textToAppend.Length - currentIndentField.Length);
            }
            else
            {
                GenerationEnvironment.Append(textToAppend);
            }
        }

        /// <summary>Write text directly into the generated output</summary>
        public void WriteLine(string textToAppend)
        {
            Write(textToAppend);
            GenerationEnvironment.AppendLine();
            endsWithNewline = true;
        }

        /// <summary>Write formatted text directly into the generated output</summary>
        public void Write(string format, params object[] args)
        {
            Write(string.Format(CultureInfo.CurrentCulture, format, args));
        }

        /// <summary>Write formatted text directly into the generated output</summary>
        public void WriteLine(string format, params object[] args)
        {
            WriteLine(string.Format(CultureInfo.CurrentCulture, format, args));
        }

        /// <summary>Increase the indent</summary>
        public void PushIndent(string indent)
        {
            if (indent == null)
            {
                throw new ArgumentNullException("indent");
            }

            currentIndentField = currentIndentField + indent;
            indentLengths.Add(indent.Length);
        }

        /// <summary>Remove the last indent that was added with PushIndent</summary>
        public string PopIndent()
        {
            string returnValue = "";
            if (indentLengths.Count > 0)
            {
                int indentLength = indentLengths[indentLengths.Count - 1];
                indentLengths.RemoveAt(indentLengths.Count - 1);
                if (indentLength > 0)
                {
                    returnValue = currentIndentField.Substring(currentIndentField.Length - indentLength);
                    currentIndentField = currentIndentField.Remove(currentIndentField.Length - indentLength);
                }
            }

            return returnValue;
        }

        /// <summary>Remove any indentation</summary>
        public void ClearIndent()
        {
            indentLengths.Clear();
            currentIndentField = "";
        }

        #endregion

        #region ToString Helpers

        /// <summary>Utility class to produce culture-oriented representation of an object as a string.</summary>
        public class ToStringInstanceHelper
        {
            /// <summary>Gets or sets format provider to be used by ToStringWithCulture method.</summary>
            public IFormatProvider FormatProvider
            {
                get { return formatProviderField; }
                set
                {
                    if (value != null)
                    {
                        formatProviderField = value;
                    }
                }
            }

            private IFormatProvider formatProviderField = CultureInfo.InvariantCulture;

            /// <summary>
            ///     This is called from the compile/run appdomain to convert objects within an expression
            ///     block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if (objectToConvert == null)
                {
                    throw new ArgumentNullException("objectToConvert");
                }

                Type t = objectToConvert.GetType();
                MethodInfo method = t.GetMethod("ToString", new[]
                {
                    typeof(IFormatProvider)
                });
                if (method == null)
                {
                    return objectToConvert.ToString();
                }

                return (string) method.Invoke(objectToConvert, new object[]
                {
                    formatProviderField
                });
            }
        }

        private readonly ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();

        /// <summary>Helper to produce culture-oriented representation of an object as a string</summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get { return toStringHelperField; }
        }

        #endregion
    }

    #endregion
}
